GET http://localhost:3003/api/blogs

### 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test", 
  "author": "jemcv",
  "url": "example.com",
  "likes": "12345678910"
}

###
DELETE http://localhost:3003/api/blogs/6600ec683c65d10d58e220f6

###
PUT http://localhost:3003/api/blogs/65ff48a487b80385a2ed302f
Content-Type: application/json

{
  "title": "Test", 
  "author": "jemcv",
  "url": "example.com",
  "likes": "1111111111"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root123",
  "name": "root",
  "password": "test"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog for Root Test",
  "author": "Test Author",
  "url": "http://testblog.com",
  "likes": 10,
  "userId": "6600ec5b3c65d10d58e220f3"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root123",
  "password": "test"
}


### 
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QxMjMiLCJpZCI6IjY2MDNiOWQ3ZTAwZTdkMGJlNTM3Y2ZlOCIsImlhdCI6MTcxMTUyMDIyNCwiZXhwIjoxNzExNTIzODI0fQ.SsNc2sgyn4uUybigEGtaCmzHEKV9Rb1jV_zK0EmQQ0M

{
  "title": "For deletion blog test",
  "author": "Next Author",
  "url": "http://testblog.com",
  "likes": 100
}

###
DELETE http://localhost:3003/api/blogs/6603b9f0e00e7d0be537cfec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2MDBlM2VjNjJjMTYxYTBhMDI4MWU4NiIsImlhdCI6MTcxMTUxOTkzNywiZXhwIjoxNzExNTIzNTM3fQ.KtfyfJoZv5NmflGcCDsmVGaBn1pVE5SJ1p8qbvWessU
