GET http://localhost:3003/api/blogs

### 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test", 
  "author": "jemcv",
  "url": "example.com",
  "likes": "12345678910"
}

###
DELETE http://localhost:3003/api/blogs/10987ba71b54a676234d17fb

###
PUT http://localhost:3003/api/blogs/65ff48a487b80385a2ed302f
Content-Type: application/json

{
  "title": "Test", 
  "author": "jemcv",
  "url": "example.com",
  "likes": "1111111111"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "root",
  "password": "test"
}